page_title: Plotagon
baseurl: /website/

ios_app_id: 883190178

app_icon: assets/icons/icon.jpg
description: Turn your story into a movie with Plotagon.
company_name: Plotagon
enable_smart_app_banner: true # Enable smart banner at top of page on mobile devices.

links: [
  { "url": "/", "title": "Mobile App" },
  { "url": "/desktop/", "title": "Desktop App" }
]

footer_links: [
  { "url": "/about/", "title": "About" },
  { "url": "/privacypolicy/", "title": "Privacy Policy" }
]

email_address: 
facebook_username:
instagram_username:
twitter_username:
github_username:
youtube_username:

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black       # blue, black, yellow, coral or white.
body_background_color                     : "#ffffff"
link_color                                : "#d74569"
app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"
feature_title_color                       : "#000000"
feature_text_color                        : "#666666"
feature_icons_foreground_color            : "#d74569"
feature_icons_background_color            : "#fff1fb"
social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"
footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown