page_title: Plotagon
baseurl: /website/

favicon: assets/icons/company-logo.png
description: Turn your story into a movie with Plotagon.
company_name: Plotagon
ios_app_id: 883190178
enable_smart_app_banner: true

google_tag_id: GTM-KJCXG9J

links: [
  { "url": "/", "title": "Mobile App" },
  { "url": "/desktop/", "title": "Desktop App" }
]

footer_links: [
  { "url": "/about/", "title": "About" },
  { "url": "/privacy-policy/", "title": "Privacy Policy" },
  { "url": "/commercial-license/", "title": "Commercial License" },
  { "url": "/terms-of-use/", "title": "Terms of Use" },
]

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_overlay                             : "linear-gradient(-30deg, #618ea0, #383838)"

device_color                              : black
body_background_color                     : "#ffffff"
link_color                                : "#9a2a46"
app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"
feature_title_color                       : "#000000"
feature_text_color                        : "#666666"
footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-redirect-from